apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-clipo-api
  labels:
    app: hackathon-clipo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-clipo-api
  template:
    metadata:
      labels:
        app: hackathon-clipo-api
    spec:
      containers:
        - name: clipo-api
          image: limalucas99/hackathon-clipo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: Database__Host
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: DB_HOST
            - name: Database__Name
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: DB_NAME
            - name: Database__User
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: DB_USER
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: DB_PASSWORD
            - name: Auth__Secret
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: Auth__Secret
            - name: EmailSettings__SmtpServer
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: EmailSettings__SmtpServer
            - name: EmailSettings__Port
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: EmailSettings__Port
            - name: EmailSettings__User
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: EmailSettings__User
            - name: EmailSettings__Password
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: EmailSettings__Password
            - name: AWS__Region
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: AWS__Region
            - name: AWS__AccessKeyId
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: AWS__AccessKeyId
            - name: AWS__SecretAccessKey
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: AWS__SecretAccessKey
            - name: AWS__SessionToken
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: AWS__SessionToken
            - name: AWS__S3__BucketName
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: AWS__S3__BucketName
            - name: AWS__UploadEnabled
              valueFrom:
                secretKeyRef:
                  name: clipo-secrets
                  key: AWS__UploadEnabled
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
