apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clipo-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: clipo-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: clipo-db-secret
        property: db_host
    - secretKey: DB_USER
      remoteRef:
        key: clipo-db-secret
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: clipo-db-secret
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: clipo-db-secret
        property: db_name
    - secretKey: Auth__Secret
      remoteRef:
        key: clipo-db-secret
        property: shared_secret
    - secretKey: EmailSettings__SmtpServer
      remoteRef:
        key: clipo-db-secret
        property: EmailSettings__SmtpServer
    - secretKey: EmailSettings__Port
      remoteRef:
        key: clipo-db-secret
        property: EmailSettings__Port
    - secretKey: EmailSettings__User
      remoteRef:
        key: clipo-db-secret
        property: EmailSettings__User
    - secretKey: EmailSettings__Password
      remoteRef:
        key: clipo-db-secret
        property: EmailSettings__Password
    - secretKey: AWS__Region
      remoteRef:
        key: clipo-db-secret
        property: AWS__Region
    - secretKey: AWS__AccessKeyId
      remoteRef:
        key: clipo-db-secret
        property: AWS__AccessKeyId
    - secretKey: AWS__SecretAccessKey
      remoteRef:
        key: clipo-db-secret
        property: AWS__SecretAccessKey
    - secretKey: AWS__SessionToken
      remoteRef:
        key: clipo-db-secret
        property: AWS__SessionToken
    - secretKey: AWS__S3__BucketName
      remoteRef:
        key: clipo-db-secret
        property: AWS__S3__BucketName
    - secretKey: AWS__UploadEnabled
      remoteRef:
        key: clipo-db-secret
        property: AWS__UploadEnabled
