apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clipo-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: clipo-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: clipo-db-secret
        property: db_host
    - secretKey: DB_USER
      remoteRef:
        key: clipo-db-secret
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: clipo-db-secret
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: clipo-db-secret
        property: db_name
