apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hackathon-clipo-api-hpa
  labels:
    app: hackathon-clipo-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hackathon-clipo-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50   
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50   
